### ISSUE TITLE
divider is limited to 3 < divider < 901 while AN619 and AN1234 state a range of  8+1/1,048,575 and 2048.

### ISSUE THREAD

**Issue by thefloe1** [adafruit/Adafruit_CircuitPython_SI5351#18]
https://github.com/adafruit/Adafruit_CircuitPython_SI5351/blob/92cdb316da9892aa7df41b634e4379aebfb89bb7/adafruit_si5351.py#L309

divider is limited to 3 < divider < 901 while AN619 and AN1234 state a range of  8+1/1,048,575 and 2048.

**Comment by stoltzmr** [comment]
Hi There, I have the same issue. Any advice? I need to be able to divide by 2048 yet 901 seems the limit in this library..

**Comment by jepler** [comment]
I've been unable to determine where the 901 number comes from.  If changing the limit to 2048 works, then we would be happy consider a pull request to change the value.

(I do have one _guess_, https://www.silabs.com/documents/public/application-notes/AN619.pdf states that a correction *to the pll multiplier limits* was changed from 900 to 90 in revision 0.2.  The limitation of 900 wouldn't have made much sense applied to the PLLs, so the implementor of the library may have guessed that it was intended instead to apply to the multisynth divider)

**Comment by jepler** [comment]
My own Adafruit SI5351 does seem to work with `pll_a` configured with divider=24 (600MHz) and `clock_0` configured to divide by 2048, giving about 292.968kHz (my counter reads 292.9612kHz)

Setting the r_divider to the maximum value R_DIV_128 gives nominal 2.2888184kHz, measured 2.28876kHz.

So, yes, I'd say based my own testing together with the application note information, we should change the divider limit.  @thefloe1 @stoltzmr are one of you able to prepare a pull request to make this improvement?

**Comment by stoltzmr** [comment]
Hi ! 
@jepler 
I'd be happy to open a 'Pull Request'. I am very new to Github - any pointers on where I can submit such? What would you expect to see in the request? Thanks so much!

**Comment by thefloe1** [comment]
@stoltzmr: thanks you, but I just made a pull request.

**Comment by stoltzmr** [comment]
@thefloe1 Aah! Thanks so much ;-)

**Comment by stoltzmr** [comment]
@thefloe1 Quick novice question: I realize this is closed and I note your pull request. How long until this ends up in the code repositories from which I can update? I see the 1.2.6 is still the last version so would not yet contain this new request. Thanks!

**Comment by jepler** [comment]
@dherrada can you release this library when you have a chance?

**Comment by stoltzmr** [comment]
Thank you Jeff. Will this change also apply to the Arduino implementation?

Regards

**Comment by evaherrada** [comment]
Just released it

**Comment by evaherrada** [comment]
@stoltzmr It will not unless someone makes those changes to the Arduino library assuming it also has that issue.

**Comment by stoltzmr** [comment]
Ok, thanks for the clarification! Much appreciated.

**Comment by stoltzmr** [comment]
Thanks so much!
