### ISSUE TITLE
Change asserts to exceptions

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_SI5351#20]
Not urgent. Just noticed this lib is still using asserts.
https://circuitpython.readthedocs.io/en/latest/docs/design_guide.html#exceptions-and-asserts

**Comment by jposada202020** [comment]
@caternuson just for my info, what is the goal here, use exceptions instead of assert n the library?. thanks :)

**Comment by caternuson** [comment]
Yep. See linked design guide info. Other CP libs could also be good reference. In general, this is a trivial change. I'll add a good first issue tag also FWIW.

**Comment by jposada202020** [comment]
will do, thanks :)

**Comment by jposada202020** [comment]
solved by #21

**Comment by caternuson** [comment]
Thanks!
