### ISSUE TITLE
Thank you for your work. But why didn't you remake another library? the frequency setting is clearer.

### ISSUE THREAD

**Issue by ingfa** [adafruit/Adafruit_CircuitPython_SI5351#25]
https://github.com/etherkit/Si5351Arduino

**Comment by dhalbert** [comment]
We have our own Arduino library here: https://github.com/adafruit/Adafruit_Si5351_Library.

Are you suggesting that this CircuitPython library might have been modeled on the library you linked to? Feel free to suggest improvements or additions to the API, via issue or a pull request.

**Comment by tekktrik** [comment]
Closing because a specific feature can be suggested separately.
