### ISSUE TITLE
typo: Assertion error when fractional pll denominator is 0xFFFFF

### ISSUE THREAD

**Issue by phrogger** [adafruit/Adafruit_CircuitPython_SI5351#6]
Line 216 in "adafruit_si5351.py" currently says:
	 assert 0 < denominator < 0xFFFFF  # Prevent divide by zero.

Which is an attempt to throw an assertion when the denominator is zero, or out of bounds.
The spec sheet says that 1048575 = 0xFFFFF is the maximum denominator allowed, and is therefore valid.
A denominator greater than 1048575 = 0xFFFFF should be asserted as an error.

The line should be modified to be:
	 assert 0 < denominator <= 0xFFFFF  # Prevent divide by zero.

I have made this change using Feather M4 Express, running CP 4.0.2, driving an Adafruit Si5351A breakout board and verified that the Si5351A works correctly as expected with denominator 0xFFFFF.

**Comment by ladyada** [comment]
thanks for the note, want to submit a PR for the fix?

**Comment by phrogger** [comment]
Sure.
Do you want me to fix the other open issue at the same time?
--- Graham

**Comment by ladyada** [comment]
ooh yeah, if you can knock both out and try em, this is not a very commonly used library but we do want it right :)

**Comment by sommersoft** [comment]
Fixed by #7
